//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.03 at 08:27:16 PM CET 
//


package org.posithing.ssd.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.posithing.ssd.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TeacherSubject_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "teacherSubject");
    private final static QName _Schoolschedule_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "schoolschedule");
    private final static QName _Teacher_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "teacher");
    private final static QName _Option_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "option");
    private final static QName _Options_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "options");
    private final static QName _Classes_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "classes");
    private final static QName _TimeSlotsAssignment_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "timeSlotsAssignment");
    private final static QName _Subjects_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "subjects");
    private final static QName _Subject_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "subject");
    private final static QName _ForClass_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "forClass");
    private final static QName _Class_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "class");
    private final static QName _TimeSlotAssignment_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "timeSlotAssignment");
    private final static QName _Teachers_QNAME = new QName("http://www.posithing.com/schoolschedulemanager/", "teachers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.posithing.ssd.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link TimeSlotsPerDay }
     * 
     */
    public TimeSlotsPerDay createTimeSlotsPerDay() {
        return new TimeSlotsPerDay();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link TimeSlotsAssignmentType }
     * 
     */
    public TimeSlotsAssignmentType createTimeSlotsAssignmentType() {
        return new TimeSlotsAssignmentType();
    }

    /**
     * Create an instance of {@link SubjectsType }
     * 
     */
    public SubjectsType createSubjectsType() {
        return new SubjectsType();
    }

    /**
     * Create an instance of {@link TeacherSubjectType }
     * 
     */
    public TeacherSubjectType createTeacherSubjectType() {
        return new TeacherSubjectType();
    }

    /**
     * Create an instance of {@link ClassesType }
     * 
     */
    public ClassesType createClassesType() {
        return new ClassesType();
    }

    /**
     * Create an instance of {@link SchoolDays }
     * 
     */
    public SchoolDays createSchoolDays() {
        return new SchoolDays();
    }

    /**
     * Create an instance of {@link SchoolScheduleType }
     * 
     */
    public SchoolScheduleType createSchoolScheduleType() {
        return new SchoolScheduleType();
    }

    /**
     * Create an instance of {@link TeachersType }
     * 
     */
    public TeachersType createTeachersType() {
        return new TeachersType();
    }

    /**
     * Create an instance of {@link ForClassType }
     * 
     */
    public ForClassType createForClassType() {
        return new ForClassType();
    }

    /**
     * Create an instance of {@link TimeSlotAssignmentType }
     * 
     */
    public TimeSlotAssignmentType createTimeSlotAssignmentType() {
        return new TimeSlotAssignmentType();
    }

    /**
     * Create an instance of {@link OptionsType }
     * 
     */
    public OptionsType createOptionsType() {
        return new OptionsType();
    }

    /**
     * Create an instance of {@link TeacherType }
     * 
     */
    public TeacherType createTeacherType() {
        return new TeacherType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeacherSubjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "teacherSubject")
    public JAXBElement<TeacherSubjectType> createTeacherSubject(TeacherSubjectType value) {
        return new JAXBElement<TeacherSubjectType>(_TeacherSubject_QNAME, TeacherSubjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchoolScheduleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "schoolschedule")
    public JAXBElement<SchoolScheduleType> createSchoolschedule(SchoolScheduleType value) {
        return new JAXBElement<SchoolScheduleType>(_Schoolschedule_QNAME, SchoolScheduleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeacherType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "teacher")
    public JAXBElement<TeacherType> createTeacher(TeacherType value) {
        return new JAXBElement<TeacherType>(_Teacher_QNAME, TeacherType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "option")
    public JAXBElement<OptionType> createOption(OptionType value) {
        return new JAXBElement<OptionType>(_Option_QNAME, OptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "options")
    public JAXBElement<OptionsType> createOptions(OptionsType value) {
        return new JAXBElement<OptionsType>(_Options_QNAME, OptionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "classes")
    public JAXBElement<ClassesType> createClasses(ClassesType value) {
        return new JAXBElement<ClassesType>(_Classes_QNAME, ClassesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeSlotsAssignmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "timeSlotsAssignment")
    public JAXBElement<TimeSlotsAssignmentType> createTimeSlotsAssignment(TimeSlotsAssignmentType value) {
        return new JAXBElement<TimeSlotsAssignmentType>(_TimeSlotsAssignment_QNAME, TimeSlotsAssignmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "subjects")
    public JAXBElement<SubjectsType> createSubjects(SubjectsType value) {
        return new JAXBElement<SubjectsType>(_Subjects_QNAME, SubjectsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "subject")
    public JAXBElement<SubjectType> createSubject(SubjectType value) {
        return new JAXBElement<SubjectType>(_Subject_QNAME, SubjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "forClass")
    public JAXBElement<ForClassType> createForClass(ForClassType value) {
        return new JAXBElement<ForClassType>(_ForClass_QNAME, ForClassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "class")
    public JAXBElement<ClassType> createClass(ClassType value) {
        return new JAXBElement<ClassType>(_Class_QNAME, ClassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeSlotAssignmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "timeSlotAssignment")
    public JAXBElement<TimeSlotAssignmentType> createTimeSlotAssignment(TimeSlotAssignmentType value) {
        return new JAXBElement<TimeSlotAssignmentType>(_TimeSlotAssignment_QNAME, TimeSlotAssignmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TeachersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.posithing.com/schoolschedulemanager/", name = "teachers")
    public JAXBElement<TeachersType> createTeachers(TeachersType value) {
        return new JAXBElement<TeachersType>(_Teachers_QNAME, TeachersType.class, null, value);
    }

}
