//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.03 at 08:27:16 PM CET 
//


package org.posithing.ssd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{http://www.posithing.com/schoolschedulemanager/}schoolDays" minOccurs="0"/>
 *         &lt;element ref="{http://www.posithing.com/schoolschedulemanager/}timeSlotsPerDay" minOccurs="0"/>
 *         &lt;element ref="{http://www.posithing.com/schoolschedulemanager/}option" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OptionsType", propOrder = {
    "schoolDays",
    "timeSlotsPerDay",
    "option"
})
public class OptionsType {

    protected SchoolDays schoolDays;
    protected TimeSlotsPerDay timeSlotsPerDay;
    protected List<OptionType> option;

    /**
     * Gets the value of the schoolDays property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolDays }
     *     
     */
    public SchoolDays getSchoolDays() {
        return schoolDays;
    }

    /**
     * Sets the value of the schoolDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolDays }
     *     
     */
    public void setSchoolDays(SchoolDays value) {
        this.schoolDays = value;
    }

    /**
     * Gets the value of the timeSlotsPerDay property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSlotsPerDay }
     *     
     */
    public TimeSlotsPerDay getTimeSlotsPerDay() {
        return timeSlotsPerDay;
    }

    /**
     * Sets the value of the timeSlotsPerDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSlotsPerDay }
     *     
     */
    public void setTimeSlotsPerDay(TimeSlotsPerDay value) {
        this.timeSlotsPerDay = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the option property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptionType }
     * 
     * 
     */
    public List<OptionType> getOption() {
        if (option == null) {
            option = new ArrayList<OptionType>();
        }
        return this.option;
    }

}
